### ISSUE TITLE
node-php-awesome-server doesnot load php server when packaged with electeon-builder

### ISSUE THREAD

**Issue by Muhammad-Taif-Khan** [darklightcode/PHP-Built-in-web-server-Router#2]
Hi i used your package node-php-awesome-server  its working fine in development but when i package the app with electron-builder. The  it does not connect to server . And the 'connect' event never fires.

**Comment by darklightcode** [comment]
The machine that's running the process must have php installed to work. 
Have you bundled a version of PHP with the electron app ? 
An unpacked version of php in the electron dist folder should exist, and when you start the app in production/testing make sure to configure the "**bin**" option to point to php.exe from the php folder.
```
{ // production config
   bin: "/absolute/path/to/electron-dist/php/php.exe",
   ...
}
```
Info: 
 - When packing: Use a zip file with the php binaries, include it in dist while packing the app
 - On first run of the app: Unpack the php archive in the project root if the php folder doesn't exist.

**Comment by Muhammad-Taif-Khan** [comment]
In production i include php binaries folder as extraResources and point to that path. I load the php scripts like this.
`phpserver.on ('connect', ()=>{
mainWindow.loadUrl ("http:/127.0.0.0:5000")
})`

But the event "connect" does not fire. And the url does not load.

**Comment by Muhammad-Taif-Khan** [comment]
Below is the code that loads the php binaries and php server in development and in production.
`const Server = require('node-php-awesome-server');
const PORT = 5342,
      HOST = "127.0.0.1";`

`const ServerUrl = `http://${HOST}:${PORT}`;
let PhpServer = null;`

`function setPhpPath(){
  if(app.isPackaged){
   return  path.join(process.resourcesPath, "src/php/php.exe");
  }
  return path.join(__dirname,'php/php.exe');
}`

 `PhpServer = new Server({
  host:HOST,
  port:PORT,
  root:path.join(__dirname,'/www/public'),
  bin:setPhpPath(),
  router: path.join(__dirname,'/www/server.php')
});`

  `//load the app when a server gets connected.
 PhpServer.on('connect', ()=>{
  mainWindow.loadURL(ServerUrl);
 });`

**Comment by darklightcode** [comment]
Update the package to **1.5.0** and let me know how it goes.

**Comment by Muhammad-Taif-Khan** [comment]
> Update the package to **1.5.0** and let me know how it goes.

It didn't work!

**Comment by darklightcode** [comment]
Do you have a repo sample, some minimal example i can try ?

**Comment by Muhammad-Taif-Khan** [comment]
> Do you have a repo sample, some minimal > example i can try ?

I can send you link of google drive to see the code

**Comment by darklightcode** [comment]
Sure, something i can clone/install to check what's happening

**Comment by Muhammad-Taif-Khan** [comment]
I dont have a github repo. Its a not a large app, it is just for testing purposes. I will share the Google drive link to source code then you can test it.

**Comment by Muhammad-Taif-Khan** [comment]
This is the link to source code:
https://drive.google.com/file/d/13heHXqmf8Z4bTjWwrErCbhq_yQ7PP2Kk/view?usp=sharing

**Comment by darklightcode** [comment]
Thanks, i've just tried it. The connect event didn't fire because npas could not find the **root** and **router** file, they were packed into asar.
Your code was good to go, paths set correctly. The only change i've made was in **package.json** add **"asar": false** under the **build** key, it might not be what you really wanted, but there's no other way around since the php router requires valid paths for those two:
```
"build": {
   "asar": false,
    ...
}
```

**Comment by Muhammad-Taif-Khan** [comment]
You are right it works if asar is false. But i wanted it to work with asar : true.
By the way thanks for your time.
